import React from 'react';
import Head from "next/head";
import AboutDetails from "../features/about/components/AboutDetails";
import Header from "../layouts/Header";
import Cursor from "../components/ui/Cursor";
import Projects from "../features/projects/components/Projects";
import Sidebar from "../layouts/Sidebar";
import AboutPortfolio from "../features/about/components/AboutPortfolio";
import Clients from "../features/about/components/Clients";

function About() {
    return (
        <div>
            <Head>
                <title> Muriel - Creative </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='grid'>
                <Header/>
                <Cursor/>
                <main className='grid__main'>
                    <AboutDetails/>
                    <AboutPortfolio/>
                    <Clients/>
                </main>
                <Sidebar/>
            </div>
        </div>
    );
}

export default About;